create database projects;
use projects;
select * from categories;
select * from customers;
select * from orderdetails;
select * from orders;
select * from products;
select * from store_Employees;
select * from suppliers;


-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

-- 1.How many unique customers have placed orders?
SELECT COUNT(DISTINCT o.customerid) AS unique_customers
FROM orders o;


-- 2. Which customers have placed the highest number of orders?

select c.name,c.customerid,count(*) as count_ from orders o
join customers c on 
c.customerid=o.customerid
group by c.customerid,c.name
order by count(*) desc limit 1 ;


-- 3.What is the total and average purchase value per customer?
SELECT 
    c.customerid,
    c.name,
    SUM(od.totalprice) AS total_purchase,
    AVG(od.totalprice) AS avg_purchase
FROM customers c
JOIN orders o ON c.customerid = o.customerid
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY c.customerid, c.name
order by total_purchase ;



-- 4.Who are the top 5 customers by total purchase amount
SELECT 
    c.name,
    SUM(od.totalprice) AS total_spent
FROM customers c
JOIN orders o ON c.customerid = o.customerid
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY c.customerid, c.name
ORDER BY total_spent DESC
LIMIT 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- 5.How many products exist in each category?
select c.categoryname, count(p.name) from products p 
join categories c on 
c.categoryid=p.categoryid
group by c.categoryname;

-- What is the average price of products by category? 
select c.categoryname, avg(p.price) as average_price from products p 
join categories c on 
c.categoryid=p.categoryid
group by c.categoryname;

-- 6.Which products have the highest total sales volume (by quantity)?
SELECT 
    p.name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN orderdetails od ON p.productid = od.productid
GROUP BY p.productid, p.name
ORDER BY total_quantity_sold DESC;


-- 7.What is the total revenue generated by each product?
SELECT p.ProductID,p.Name,SUM(od.Quantity * od.Priceeach) AS TotalRevenue
FROM OrderDetails od
JOIN Products p 
    ON od.ProductID = p.ProductID
GROUP BY 
    p.ProductID, 
    p.Name
ORDER BY TotalRevenue DESC;

-- 8.How do product sales vary by category and supplier?
SELECT c.categoryname,s.suppliername,sum(od.quantity),SUM(od.quantity * od.priceeach) AS total_sales
FROM orderdetails od
JOIN products p ON od.productid = p.productid
JOIN categories c ON p.categoryid = c.categoryid
JOIN suppliers s ON p.supplierid = s.supplierid
GROUP BY c.categoryname, s.suppliername
ORDER BY total_sales DESC;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- 9.How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;

-- 10.What is the average value per order?
SELECT orderid,AVG(order_total) AS avg_order_value
FROM (
    SELECT od.orderid, SUM(od.totalprice) AS order_total
    FROM orderdetails od
    GROUP BY od.orderid
) t
group by orderid;

-- 11.On which dates were the most orders placed?
select orderdate ,count(*) as totalorders
 from orders
 group by orderdate
 order by totalorders desc;
 


-- If stored as VARCHAR and needs conversion (MySQL STR_TO_DATE example for 'DD-MM-YYYY'):
-- adjust format string according to your stored format
-- 12
SELECT orderdate AS the_date, COUNT(*) AS orders_on_date
FROM orders
GROUP BY the_date
ORDER BY orders_on_date DESC
LIMIT 10;
-- 13
select left(o.orderdate,7) as ordermonth,count(distinct o.orderid) as order_volume,
sum(od.quantity*od.priceeach) as totalrevenue
from orders o 
join orderdetails od on o.orderid=od.orderid
group by ordermonth
order by ordermonth;

-- 14.How do order patterns vary across weekdays and weekends?
SELECT
    CASE
        WHEN DAYOFWEEK(STR_TO_DATE(o.OrderDate, '%m/%d/%Y')) IN (1, 7) THEN 'Weekend'      -- Saturday or Sunday
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.OrderID) AS orders_count, SUM(od.TotalPrice) AS revenue
FROM Orders o
JOIN OrderDetails od 
    ON o.OrderID = od.OrderID
GROUP BY day_type;



-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- 15.How many suppliers are there in the database?
SELECT COUNT(*) AS supplier_count
FROM suppliers;

-- 16.Which supplier provides the most products?
SELECT s.supplierid, s.suppliername, COUNT(p.productid) AS product_count
FROM suppliers s
LEFT JOIN products p ON p.supplierid = s.supplierid
GROUP BY s.supplierid, s.suppliername
ORDER BY product_count DESC
LIMIT 1;

-- 17.What is the average price of products from each supplier?
SELECT s.supplierid, s.suppliername, AVG(p.price) AS avg_product_price
FROM suppliers s
JOIN products p ON p.supplierid = s.supplierid
GROUP BY s.supplierid, s.suppliername
ORDER BY avg_product_price DESC;

-- 18.Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.supplierid,
    s.suppliername,
    SUM(od.quantity * od.priceeach) AS supplier_revenue
FROM orderdetails od
JOIN products p ON od.productid = p.productid
JOIN suppliers s ON p.supplierid = s.supplierid
GROUP BY s.supplierid, s.suppliername
ORDER BY supplier_revenue DESC;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- 19.How many employees have processed orders?
SELECT COUNT(DISTINCT employeeid) AS employees_with_orders
FROM orders
WHERE employeeid IS NOT NULL;

-- 20.Which employees have handled the most orders?
SELECT e.employeeid, e.name, COUNT(o.orderid) AS orders_handled
FROM store_employees e
JOIN orders o ON e.employeeid = o.employeeid
GROUP BY e.employeeid, e.name
ORDER BY orders_handled DESC;


-- 21.What is the total sales value processed by each employee?
SELECT e.employeeid,e.name,SUM(od.totalprice) AS total_sales_processed
FROM store_employees e
JOIN orders o ON e.employeeid = o.employeeid
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY e.employeeid, e.name
ORDER BY total_sales_processed DESC;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- 22.What is the average quantity ordered per product?

SELECT p.productid,p.name,AVG(od.quantity) AS avg_quantity_per_line
FROM products p
JOIN orderdetails od ON p.productid = od.productid
GROUP BY p.productid, p.name
ORDER BY avg_quantity_per_line DESC;

-- 23.What is the relationship between quantity ordered and total price?
SELECT priceeach,quantity,totalprice
FROM orderdetails;


-- 24.How does the unit price vary across products and orders?

select p.productid ,p.name,od.priceeach from  products p 
join orderdetails od on 
od.productid=p.productid ;







